Add .crypto resolution for Verified Twitter
MyEtherWallet/MyEtherWallet pull request #2591
Opened 2020-09-22 19:12 UTC by sudoryan

Shows if a .crypto domain is Twitter Verified for resolution.
Test with beresnev.crypto sending ETH.

2020-10-08 19:13 UTC, gamalielhere commented on src/directives/AddrResolver.js
> +          console.log(err);
Please remove console

2020-10-08 19:14 UTC, gamalielhere requested changes
Everything looks good, just need to remove the console and the yarn.lock

2020-10-15 18:08 UTC, kvhnuke requested changes

2020-10-15 18:08 UTC, kvhnuke commented on src/directives/AddrResolver.js
> +                )} <a href="https://chain.link/" target="_blank" style="margin-left: 5px">Chainlink</a></div>`;
add `no referrer`

2020-10-15 18:08 UTC, kvhnuke approved these changes

2020-10-15 20:43 UTC, gamalielhere commented
Included #2624

2020-10-15 20:43 UTC, closed without merging