chore: reopen display-alternative-swaps
MyEtherWallet/MyEtherWallet pull request #2715
Opened 2020-12-09 19:14 UTC by gamalielhere

### Feature

* \[x] Updated CHANGELOG.md
* \[ ] Add test cases or procedure
* \[x] Add PR label
* \[x] No hard-coded strings

2020-12-10 20:51 UTC, kvhnuke requested changes

2020-12-10 20:51 UTC, kvhnuke commented on compileBaseSwapOptions.js
> +    // if (Object.keys(this.coinGecko).length > 0) {
do we need this?

2020-12-15 23:16 UTC, SteveMieskoski approved these changes

2020-12-15 23:17 UTC, kvhnuke approved these changes

2020-12-15 23:17 UTC, merged