Bug/coolwallet pairing issue [v5]
MyEtherWallet/MyEtherWallet pull request #2808
Opened 2021-02-02 18:29 UTC by gamalielhere

### Bug

* \[x] Updated CHANGELOG.md
* \[x] Add PR label
* \[x] No hard-coded strings

2021-02-08 20:51 UTC, kvhnuke requested changes

2021-02-08 20:51 UTC, kvhnuke commented on src/wallets/hardware/coolwallet/index.js
> +    this.appPrivateKey = locStore.get('appPrivateKey')
can you make the name and key value `coolwallet-appKey`

2021-02-10 19:12 UTC, kvhnuke approved these changes

2021-02-10 19:38 UTC, SteveMieskoski approved these changes

2021-02-10 20:44 UTC, gesseekur approved these changes

2021-02-10 23:27 UTC, merged