V6/settings
MyEtherWallet/MyEtherWallet pull request #2835
Opened 2021-02-12 00:51 UTC by gamalielhere

### Devop

* \[ ] Updated CHANGELOG.md
* \[x] Add PR label
* \[x] No hard-coded strings

2021-02-24 22:38 UTC, kvhnuke requested changes

2021-02-24 22:38 UTC, kvhnuke commented on src/core/store/global/getters.js
> +const gasPrice = function (state) {
gasPrice should always return wei amount, and the place where we use it we can switch it to gwei for display purpose

2021-02-24 22:38 UTC, kvhnuke commented on src/core/store/global/getters.js
> +const gasPrice = function (state) {
this func should just be `return getGasBasedOnType(state.baseGasPrice, state.gasPriceType)`

2021-02-24 22:38 UTC, kvhnuke commented on src/modules/send/ModuleSend.vue
> +    ...mapGetters('global', ['network', 'gasPrice']),
overhere we should get gasprice in wei

2021-02-24 22:38 UTC, kvhnuke commented on src/modules/settings/ModuleSettings.vue
> +// import Notifications from './components/SettingsNotification';
commented code

2021-02-24 22:38 UTC, kvhnuke commented on src/core/store/global/getters.js
> +import web3Utils from 'web3-utils';
`import {fromWei} from 'web3-utils'`

2021-02-24 22:38 UTC, kvhnuke commented on src/modules/settings/handler/handlerSettings.js
> +const VALID_FIELDS = [
shouldn't this be just the keys of the state?

2021-02-24 22:38 UTC, kvhnuke commented on src/modules/settings/handler/handlerSettings.js
> +    newObj['gasPrice'] = stringifiedGasPrice;
I dont think this is necessary BN numbers will get converted to strings when you send through JSON.stringify also you dont have to delete localStore

2021-03-03 01:03 UTC, gesseekur approved these changes

2021-03-03 01:07 UTC, kvhnuke requested changes

2021-03-03 01:07 UTC, kvhnuke commented on src/views/layouts-wallet/TheSwapLayout.vue
> +      return toBN(this.totalGasLimit).mul(toBN(this.gasPriceGwei)).toString();
This should gaslimit*gasprice (in wei not gwei)

2021-03-04 20:23 UTC, kvhnuke approved these changes

2021-03-04 22:56 UTC, merged