V6/Fix footer CoinMarketCap link
MyEtherWallet/MyEtherWallet pull request #2957
Opened 2021-04-01 04:29 UTC by hsurf22

### Bug

* \[x] Updated CHANGELOG.md
* \[x] Add PR label
   - Fix footer CoinMarketCap link

2021-04-01 23:11 UTC, olgakup requested changes

2021-04-01 23:11 UTC, olgakup commented on src/views/components-wallet/TheWalletFooter.vue
> +              class="titlePrimary--text text-decoration--none"
Can you replace this with Coingecko 
LInk: 'https://www.coingecko.com/en'

2021-04-02 18:00 UTC, olgakup commented on src/views/components-wallet/TheWalletFooter.vue
> +              class="titlePrimary--text text-decoration--none"
I fixed that

2021-04-02 18:01 UTC, gamalielhere approved these changes

2021-04-02 18:16 UTC, olgakup approved these changes

2021-04-02 18:17 UTC, merged