V6/tx transaction flow
MyEtherWallet/MyEtherWallet pull request #3032
Opened 2021-04-19 18:13 UTC by gamalielhere

### Devop

* \[x] Updated CHANGELOG.md
* \[x] Add PR label
* \[x] No hard-coded strings

2021-04-20 00:04 UTC, hsurf22 approved these changes

2021-04-21 18:22 UTC, olgakup requested changes

2021-04-21 18:22 UTC, olgakup commented on src/modules/confirmation/ModuleConfirmation.vue
> +    // recieves an array
can you use different comments /** */

2021-04-21 18:22 UTC, olgakup commented on src/utils/web3-provider/methods/eth_sendTransaction.js
> +        // if this is true, assume transaction is swap
please use different comments /** */

2021-04-21 18:56 UTC, merged