Devop/include one inch
MyEtherWallet/MyEtherWallet pull request #3061
Opened 2021-04-30 00:22 UTC by SteveMieskoski

### Devop

* \[ ] Updated CHANGELOG.md
* \[x] Add PR label
* \[ ] No hard-coded strings

2021-05-05 18:00 UTC, gamalielhere approved these changes

2021-05-05 19:45 UTC, gesseekur commented
@SteveMieskoski can you fix build so i can test hehe

2021-05-06 22:47 UTC, kvhnuke requested changes

2021-05-06 22:47 UTC, kvhnuke commented on src/partners/oneInch/oneInch-calls.js
> +      }&dex=ONE_INCH&exchange=one_inch&platform=ios&fromContractAddress=${
`platform=web`

2021-05-12 20:32 UTC, kvhnuke requested changes

2021-05-12 20:32 UTC, kvhnuke commented on compileBaseSwapOptions.js
> +        setTimeout(function () {}, 500);
this does not wait half a sec, `await new Promise(r => setTimeout(r, 500));`

2021-05-12 20:32 UTC, kvhnuke commented on src/layouts/InterfaceLayout/containers/SwapContainer/components/ProvidersRadioSelector/ProviderInfoList/ProviderInfoList.vue
> +      console.log(name); // todo remove dev item
remove console logs

2021-05-13 20:11 UTC, kvhnuke approved these changes

2021-05-13 20:16 UTC, merged