V6/add user error message
MyEtherWallet/MyEtherWallet pull request #3103
Opened 2021-05-25 02:59 UTC by hsurf22

### Devop

* \[x] Updated CHANGELOG.md
* \[x] Add PR label
   - Add user error message

![Screenshot from 2021-05-24 19-55-45](https://user-images.githubusercontent.com/9893774/119433173-912d1a80-bcca-11eb-934d-426e92f7a5d5.png)
![Screenshot from 2021-05-24 19-55-54](https://user-images.githubusercontent.com/9893774/119433174-91c5b100-bcca-11eb-85c7-4101d5bf120a.png)

2021-05-25 19:02 UTC, olgakup requested changes

2021-05-25 19:02 UTC, olgakup commented on src/app.vue
> +import msg from '@/core/components/AppErrorMsg';
change msg to AppErrorMsg

2021-05-25 19:02 UTC, olgakup commented on src/core/components/AppErrorMsg.vue
> +          <mew-button
make this button full width

2021-05-25 19:02 UTC, olgakup commented on src/core/components/AppErrorMsg.vue
> +          <mew-button btn-size="xlarge" title="Send" class="mx-1" />
make this button full width

2021-05-25 19:04 UTC, olgakup commented
The padding between the buttons and error message looks smaller in the designs then in implementation
<img width="380" alt="Screen Shot 2021-05-25 at 12 03 23 PM" src="https://user-images.githubusercontent.com/16910687/119554187-3d194900-bd51-11eb-92c6-351d425f8e61.png">

2021-05-26 20:43 UTC, hsurf22 commented on src/core/components/AppErrorMsg.vue
> +          <mew-button
fixed

2021-05-26 20:43 UTC, hsurf22 commented on src/core/components/AppErrorMsg.vue
> +          <mew-button btn-size="xlarge" title="Send" class="mx-1" />
fixed

2021-06-08 01:28 UTC, olgakup approved these changes

2021-06-10 20:26 UTC, olgakup commented
@hsurf22 can you fix the build? and then merge this?

2021-06-14 20:47 UTC, merged