V6/fix swap btn
MyEtherWallet/MyEtherWallet pull request #3116
Opened 2021-05-28 02:06 UTC by hsurf22

### Devop

* \[x] Updated CHANGELOG.md
* \[x] Add PR label
   - Add swap button
   - Replace existing swap button with new one

![Screenshot from 2021-05-27 19-05-27](https://user-images.githubusercontent.com/9893774/119919108-9387b280-bf1e-11eb-84af-53a9b000d934.png)
![Screenshot from 2021-05-27 19-05-43](https://user-images.githubusercontent.com/9893774/119919111-94204900-bf1e-11eb-860d-ba5cf5db8133.png)

2021-06-01 19:54 UTC, olgakup commented
Please in the future do not mix features when making a pr. ENS icons could have been based of the develop branch and merged sooner

2021-06-01 19:54 UTC, olgakup commented
Please fix the build to get full review

2021-06-01 19:58 UTC, olgakup requested changes

2021-06-01 19:58 UTC, olgakup commented on src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
> +                      <v-icon color="titlePrimary" x-large>{{
can you change this to mew green color

2021-06-02 05:09 UTC, hsurf22 commented on src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
> +                      <v-icon color="titlePrimary" x-large>{{
fixed

2021-06-03 02:47 UTC, merged