V6/create wallet issue
MyEtherWallet/MyEtherWallet pull request #3174
Opened 2021-06-22 18:35 UTC by gamalielhere

### Devop

* \[x] Updated CHANGELOG.md
* \[x] Add PR label
* \[x] No hard-coded strings

2021-06-22 20:23 UTC, olgakup requested changes

2021-06-22 20:23 UTC, olgakup commented on src/modules/confirmation/ModuleConfirmation.vue
> +              textBlack2--text--text
can you change this to textBlack2--text

2021-06-24 18:20 UTC, olgakup approved these changes

2021-06-24 18:47 UTC, gesseekur approved these changes

2021-06-24 19:38 UTC, merged