V6/more UI text changes
MyEtherWallet/MyEtherWallet pull request #3193
Opened 2021-06-30 22:26 UTC by andrewdahn

More string chases
### Feature
* \[ ] Add PR label

2021-07-01 20:07 UTC, olgakup requested changes

2021-07-01 20:07 UTC, olgakup commented on src/views/layouts-default/TheBuyHardwareWalletLayout.vue
> +                      #667f9b--text
replace this with textPrimary--text

2021-07-01 20:18 UTC, olgakup commented
Also Images are not showing on xs anymore on Bug Hardware wallet 
<img width="426" alt="Screen Shot 2021-07-01 at 1 17 50 PM" src="https://user-images.githubusercontent.com/16910687/124184704-d03f5000-da6e-11eb-9b41-a2fb4fdbc720.png">

2021-07-01 21:53 UTC, andrewdahn commented on src/views/layouts-default/TheBuyHardwareWalletLayout.vue
> +                      #667f9b--text
fixed

2021-07-02 23:03 UTC, olgakup approved these changes

2021-07-06 22:16 UTC, gamalielhere approved these changes

2021-07-06 22:16 UTC, merged