fix: 🐛 show private key in print
MyEtherWallet/MyEtherWallet pull request #3239
Opened 2021-07-08 16:10 UTC by olgakup

### Bug

Private key was not shown in paper wallet for keystore and mnemonic
* \[ ] Updated CHANGELOG.md
* \[ ] Add PR label

2021-07-08 18:00 UTC, gamalielhere approved these changes

2021-07-09 16:55 UTC, kvhnuke requested changes

2021-07-09 16:55 UTC, kvhnuke commented on src/modules/balance/components/PaperWalletToDisplay.vue
> +      if (this.address && this.showPrivateKey) {
There is this.instance.isPubOnly if that is true no private key you can use that for this if statement

2021-07-09 18:59 UTC, kvhnuke approved these changes

2021-07-09 19:05 UTC, merged

2021-07-16 07:15 UTC, Badameron31 commented
This sucks