devop: 🔧 use v6 mewbuilds
MyEtherWallet/MyEtherWallet pull request #3257
Opened 2021-07-12 19:11 UTC by gamalielhere

### Devop

* \[x] Updated CHANGELOG.md
* \[X] Add PR label

2021-07-13 19:22 UTC, kvhnuke requested changes

2021-07-13 19:22 UTC, kvhnuke commented on checkBranch.sh
> +valid_branch_regex="^(feature|feat|fix|chore|devop|release|hotfix|ui|translation)\/[a-z0-9._-]+$"
can you add `sentry` in here too

2021-07-13 19:22 UTC, kvhnuke commented on commitlint.config.js
> +        'translation'
and `sentry` here then edit the devmoji.config.js to add a gitmoji. I used this to get gitmoji names https://gitmoji.dev/

2021-07-14 20:07 UTC, kvhnuke requested changes

2021-07-14 20:07 UTC, kvhnuke commented on devmoji.config.js
> +    { code: 'sentry', gitmoji: ':fire:' }
remove the `: :` inside gitmoji

2021-07-14 20:38 UTC, gesseekur approved these changes

2021-07-14 20:44 UTC, kvhnuke approved these changes

2021-07-14 21:05 UTC, merged