fix: 🐛 nft send button disable if emnpty or invalid address
MyEtherWallet/MyEtherWallet pull request #3261
Opened 2021-07-13 02:28 UTC by gamalielhere

### Bug

* \[x] Updated CHANGELOG.md
* \[x] Add PR label

2021-07-13 16:49 UTC, gesseekur commented on src/modules/nft-manager/ModuleNftManager.vue
> +          :disabled="isValid"
hrrm is this suppose to be disabled if it is not valid ?

2021-07-13 19:09 UTC, kvhnuke requested changes

2021-07-13 19:09 UTC, kvhnuke commented on src/modules/nft-manager/ModuleNftManager.vue
> +      return this.nft.isValidAddress(this.toAddress) && this.toAddress !== '';
change the isValidAddress function to check for !== ''

2021-07-14 20:11 UTC, kvhnuke approved these changes

2021-07-14 20:35 UTC, gesseekur approved these changes

2021-07-14 21:44 UTC, merged