fix: 🐛 import routes
MyEtherWallet/MyEtherWallet pull request #3291
Opened 2021-07-15 22:01 UTC by rsteubs

### Bug
* [ ] Updated CHANGELOG.md
* [ ] Add PR label

2021-07-19 17:36 UTC, andrewdahn approved these changes

2021-07-19 21:22 UTC, gamalielhere requested changes
add entry to changelog

2021-07-19 21:39 UTC, gamalielhere approved these changes

2021-07-21 03:21 UTC, kvhnuke approved these changes

2021-07-21 23:00 UTC, merged