fix: 🐛 wallet view layout bug
MyEtherWallet/MyEtherWallet pull request #3373
Opened 2021-08-06 21:57 UTC by hsurf22

### Bug

* \[x] Added entry to ./changelog
* \[x] Add PR label
   - fix wallet layout bug

https://app.asana.com/0/1125971615701970/1200742079762362

2021-08-06 22:23 UTC, rsteubs approved these changes

2021-08-06 22:40 UTC, andrewdahn approved these changes

2021-08-09 17:26 UTC, gamalielhere requested changes

2021-08-09 17:26 UTC, gamalielhere commented on CHANGELOG.md
> +* fix wallet layout bug [#3373](https://github.com/MyEtherWallet/MyEtherWallet/pull/3373)
Don't need to do this, please remove

2021-08-09 17:58 UTC, hsurf22 commented on CHANGELOG.md
> +* fix wallet layout bug [#3373](https://github.com/MyEtherWallet/MyEtherWallet/pull/3373)
Fixed

2021-08-09 18:04 UTC, gesseekur commented
can you double check w/ @olgakup ? I remember she made the padding like that on purpose

2021-08-10 20:12 UTC, gamalielhere approved these changes

2021-08-11 18:16 UTC, merged