Feat/access hardware refresh
MyEtherWallet/MyEtherWallet pull request #3398
Opened 2021-08-18 22:36 UTC by gesseekur

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted feature request?
  * \[ ] Link to issue:
* \[ ] Add test cases or procedure
* \[ ] Add PR label

2021-09-15 20:32 UTC, gamalielhere approved these changes

2021-09-17 19:13 UTC, olgakup requested changes
Not sure what happend but in the Create New Wallet screen all button text goes outside of the buttons now.
<img width="1033" alt="Screen Shot 2021-09-17 at 12 12 02 PM" src="https://user-images.githubusercontent.com/16910687/133841592-a35da176-ff7e-488c-88eb-d39ecc3c82cf.png">

2021-09-24 21:43 UTC, andrewdahn approved these changes

2021-09-24 21:44 UTC, olgakup approved these changes

2021-09-24 22:00 UTC, rsteubs approved these changes

2021-09-24 22:20 UTC, merged