fix: 🐛 add connection check
MyEtherWallet/MyEtherWallet pull request #3532
Opened 2021-11-03 19:38 UTC by rsteubs

### Bug
* \[x] Added entry to ./changelog
* \[x] Add PR label

2021-11-05 22:32 UTC, gamalielhere requested changes

2021-11-05 22:32 UTC, gamalielhere commented on src/core/store/wallet/actions.js
> +      state.instance.getConnection().disconnect();
Assign it to a variable so you wont have to call it twice.

2021-11-10 04:04 UTC, andrewdahn approved these changes

2021-11-10 20:47 UTC, gamalielhere approved these changes

2021-11-10 22:10 UTC, merged