fix: 🐛 show usd cost modal
MyEtherWallet/MyEtherWallet pull request #3563
Opened 2021-11-17 04:11 UTC by andrewdahn

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2021-11-18 23:31 UTC, hsurf22 approved these changes

2021-11-22 17:18 UTC, rsteubs commented on src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
> +    // valueUsd: {
Comments could probably be removed

2021-11-22 17:18 UTC, rsteubs approved these changes

2021-11-23 22:32 UTC, gamalielhere requested changes

2021-11-23 22:32 UTC, gamalielhere commented on src/modules/confirmation/components/ConfirmationSendTransactionDetails.vue
> +    //   type: Number,
Remove comments

2021-11-29 19:05 UTC, gamalielhere approved these changes

2021-11-29 20:58 UTC, merged