chore: 👷 updated packages
MyEtherWallet/MyEtherWallet pull request #3629
Opened 2022-01-18 19:12 UTC by jmjles

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-01-24 21:43 UTC, gamalielhere requested changes

2022-01-24 21:43 UTC, gamalielhere commented on changelog/devop-3629.md
> +  * commitlint
remove these parts

2022-01-25 19:52 UTC, gamalielhere approved these changes

2022-01-25 19:54 UTC, andrewdahn approved these changes

2022-01-25 19:56 UTC, merged