fix: 🐛 Added Mount Check
MyEtherWallet/MyEtherWallet pull request #3632
Opened 2022-01-20 19:33 UTC by jmjles

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-01-24 21:41 UTC, gamalielhere requested changes

2022-01-24 21:41 UTC, gamalielhere commented on src/modules/swap/ModuleSwap.vue
> +      if (this.mounted) {
no need for the mounted variable. just check for whether they're not null when calling `this.clear`. before calling them.

2022-01-25 22:11 UTC, gamalielhere approved these changes

2022-01-26 23:34 UTC, andrewdahn approved these changes

2022-01-27 19:34 UTC, merged