fix: popup not showing current network
MyEtherWallet/MyEtherWallet pull request #3633
Opened 2022-01-21 00:53 UTC by jmjles

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-01-24 21:38 UTC, gamalielhere requested changes

2022-01-24 21:38 UTC, gamalielhere commented on src/core/components/AppAddrQr.vue
> +      {{ $t('interface.qr.desc').replace(/ETH/g, currency) }}
use this instead: https://kazupon.github.io/vue-i18n/guide/interpolation.html#slots-syntax-usage

2022-01-24 21:38 UTC, gamalielhere commented on src/core/components/AppAddrQr.vue
> +    currency: {
you can get the currency name from 'global' store. You can fuzzy search `currencyName` to see examples.

2022-02-04 21:08 UTC, andrewdahn approved these changes

2022-02-09 00:56 UTC, gamalielhere commented
moved it to #3670

2022-02-09 00:56 UTC, closed without merging