feature: ens-dapp-balance-check
MyEtherWallet/MyEtherWallet pull request #3710
Opened 2022-03-08 20:02 UTC by NewCodeOnDaBlock

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted feature request?
  * \[ ] Link to issue:
* \[ ] Add test cases or procedure
* \[ ] Add PR label

2022-04-14 09:27 UTC, hsurf22 approved these changes

2022-04-29 17:18 UTC, gamalielhere requested changes

2022-04-29 17:18 UTC, gamalielhere commented on src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
> +      const int = setInterval(() => {
You shouldn't have to do this after adding the await.

2022-04-29 17:18 UTC, gamalielhere commented on src/dapps/ens-manager-dapp/components/register/Register.vue
> +import { EventBus } from '@/core/plugins/eventBus';
change this to the mixin

2022-05-02 17:13 UTC, gamalielhere requested changes

2022-05-02 17:13 UTC, gamalielhere commented on src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
> +        const feesAdded = Number(this.regFee) + Number(this.commitFeeInEth);
Use BigNumber or BN.

2022-05-10 20:01 UTC, gamalielhere approved these changes

2022-05-16 21:16 UTC, merged