chore: 👷 nft-gas-error-send
MyEtherWallet/MyEtherWallet pull request #3727
Opened 2022-03-11 20:58 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
  * \[ ] Link to issue:
* \[ ] Add PR label

2022-03-31 20:21 UTC, gamalielhere requested changes

2022-03-31 20:21 UTC, gamalielhere commented on src/modules/nft-manager/ModuleNftManager.vue
> +        const gasTypeFee = this.gasPriceByType(this.gasPriceType);
use the defined `this.localGasPrice`.

2022-04-05 18:54 UTC, gamalielhere approved these changes

2022-04-07 20:40 UTC, jmjles approved these changes

2022-04-07 20:43 UTC, merged