feat: ✨  eth2 keystore file generator in tools section
MyEtherWallet/MyEtherWallet pull request #3758
Opened 2022-03-30 06:31 UTC by andrewdahn

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-03-30 06:32 UTC, NewCodeOnDaBlock approved these changes

2022-03-31 21:06 UTC, gamalielhere requested changes
Change the 'Upload Keystore' texts to 'Verify Keystore'

2022-03-31 21:06 UTC, gamalielhere commented on src/modules/tools/ModuleToolsGenerateKeystore/components/StepOne.vue
> +      >
Let's remove this section as it doesn't make sense in this context

2022-04-05 18:57 UTC, gamalielhere commented on src/modules/tools/ModuleToolsGenerateKeystore/ModuleToolsGenerateKeystore.vue
> +  // watch: {
remove commented code.

2022-04-05 18:57 UTC, gamalielhere approved these changes

2022-04-07 19:22 UTC, merged