fix: 🐛 failed to fetch pool api
MyEtherWallet/MyEtherWallet pull request #3787
Opened 2022-04-15 20:11 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
* \[x] Is this a user submitted bug?
* \[x ] Add PR label

2022-04-26 22:53 UTC, gamalielhere requested changes

2022-04-26 22:53 UTC, gamalielhere commented on src/dapps/stakewise/handlers/stakewiseHandler.js
> +        reject;
reject the exception value from the catch as well.

2022-04-27 18:07 UTC, gamalielhere approved these changes

2022-05-10 20:14 UTC, andrewdahn approved these changes

2022-05-11 23:51 UTC, merged