Feature/integrate ledger x
MyEtherWallet/MyEtherWallet pull request #3797
Opened 2022-04-22 07:09 UTC by NewCodeOnDaBlock

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Add test cases or procedure
* \[ ] Add PR label

2022-04-26 21:59 UTC, gamalielhere requested changes
remove the ledger logo image since it's not used, and replace the ledger x image with a png.

2022-04-26 22:36 UTC, gamalielhere approved these changes

2022-04-27 22:29 UTC, andrewdahn approved these changes

2022-05-10 20:12 UTC, andrewdahn approved these changes

2022-05-11 22:15 UTC, merged