Devop: Buy/Sell on Moonpay & Simplex
MyEtherWallet/MyEtherWallet pull request #3844
Opened 2022-05-20 03:49 UTC by Abyscuit

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-06-02 23:05 UTC, andrewdahn approved these changes

2022-06-03 19:35 UTC, gamalielhere requested changes

2022-06-03 19:35 UTC, gamalielhere commented on connections.js
> +  'https://api.coingecko.com:443',
can probably remove this

2022-06-03 19:35 UTC, gamalielhere commented on src/modules/moon-pay/ModuleMoonPay.vue
> +      <div v-if="step == 0">
let's use strict comparisons `===`

2022-06-03 19:35 UTC, gamalielhere commented on src/modules/moon-pay/ModuleMoonPay.vue
> +        v-if="step == 1"
same here

2022-06-03 19:35 UTC, gamalielhere commented on src/modules/moon-pay/components/MoonPayBuyComponent.vue
> +      this.$emit('simplexQuote', this.simplexQuote);
you can probably change this to 1 emit by passing an array instead `this.$emit(<event>, [...,])`

2022-06-03 19:35 UTC, gamalielhere commented on src/modules/moon-pay/components/MoonPaySellComponent.vue
> +    // defaultCurrency(e) {
remove unused code.

2022-06-07 18:28 UTC, gamalielhere requested changes

2022-06-09 03:02 UTC, hsurf22 approved these changes

2022-06-16 22:51 UTC, gamalielhere approved these changes

2022-06-16 23:48 UTC, merged