Sentry: BN Error
MyEtherWallet/MyEtherWallet pull request #3878
Opened 2022-06-01 23:29 UTC by jmjles

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-06-02 19:37 UTC, Abyscuit approved these changes

2022-06-02 22:59 UTC, andrewdahn approved these changes

2022-06-03 19:29 UTC, gamalielhere requested changes

2022-06-03 19:29 UTC, gamalielhere commented on src/core/helpers/numberFormatHelper.js
> +    isNaN(number) ||
isNan doesn't seem to be defined anywhere. use lodash's `isNan` and `isNumber`

2022-06-07 18:25 UTC, gamalielhere requested changes

2022-06-07 18:25 UTC, gamalielhere commented on src/core/helpers/numberFormatHelper.js
> +    number === 'NaN'
shouldn't this be covered by isNan already?

2022-06-07 18:25 UTC, gamalielhere commented on src/core/helpers/numberFormatHelper.js
> +    number === '' ||
also you can use !isNumber for this

2022-06-08 18:50 UTC, gamalielhere approved these changes

2022-06-17 06:01 UTC, merged