feat: ✨ ens reverse lookup init
MyEtherWallet/MyEtherWallet pull request #3884
Opened 2022-06-02 19:55 UTC by NewCodeOnDaBlock

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-06-21 18:54 UTC, gamalielhere requested changes

2022-07-06 19:05 UTC, Abyscuit approved these changes

2022-07-06 19:56 UTC, kvhnuke requested changes

2022-07-06 19:56 UTC, kvhnuke commented on src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
> +          ensAddress: getEnsAddress(this.network.type.chainID.toString())
you can get the ens address from the network object, cz I think getEnsAddress might not have all chainIds

2022-07-06 19:56 UTC, kvhnuke commented on src/dapps/ens-manager-dapp/components/reverse/EnsReverseLookup.vue
> +          ensAddress: getEnsAddress(this.network.type.chainID.toString())
same as above

2022-07-06 19:56 UTC, kvhnuke commented on src/dapps/ens-manager-dapp/TheENSManagerLayout.vue
> +          ensAddress: getEnsAddress(this.network.type.chainID.toString())
`this.network.type.ens.registry`

2022-07-13 01:16 UTC, hsurf22 approved these changes

2022-07-26 21:44 UTC, merged