fix: 🐛 sentry undefined to token amount
MyEtherWallet/MyEtherWallet pull request #3896
Opened 2022-06-07 04:41 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
* \[ ] Add PR label

2022-06-07 18:23 UTC, gamalielhere requested changes

2022-06-07 18:23 UTC, gamalielhere commented on src/core/store/wallet/mutations.js
> +  // state.address = wallet.getAddressString();
revert

2022-06-07 18:56 UTC, gamalielhere approved these changes

2022-06-08 23:40 UTC, hsurf22 approved these changes

2022-06-17 00:53 UTC, merged