fix: display address in drop down
MyEtherWallet/MyEtherWallet pull request #3899
Opened 2022-06-07 23:11 UTC by andrewdahn

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-06-08 19:38 UTC, gamalielhere requested changes

2022-06-08 19:38 UTC, gamalielhere commented on src/modules/address-book/ModuleAddressBook.vue
> +              address: toChecksumAddress(this.$store.state.wallet.address),
can you import the address from the state instead? change it for all the files as well.

2022-06-08 23:42 UTC, hsurf22 approved these changes

2022-06-15 21:31 UTC, Abyscuit approved these changes

2022-06-16 22:50 UTC, merged