fix: 🐛 gas estimate max bug
MyEtherWallet/MyEtherWallet pull request #3905
Opened 2022-06-09 20:58 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-06-09 22:48 UTC, gamalielhere requested changes

2022-06-09 22:48 UTC, gamalielhere commented on package-audit.js
> +  '@cosmjs/amino'
actually dont need this

2022-06-09 22:48 UTC, gamalielhere commented on package-test.js
> +  '@commitlint/config-conventional',
pull in develop as some of these has been fixed already.

2022-06-15 23:14 UTC, Abyscuit approved these changes

2022-06-21 19:19 UTC, gamalielhere approved these changes

2022-07-01 21:26 UTC, merged