fix: fix ethblocks tx fee popup
MyEtherWallet/MyEtherWallet pull request #3906
Opened 2022-06-09 22:00 UTC by andrewdahn

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-06-14 23:25 UTC, gamalielhere requested changes

2022-06-14 23:25 UTC, gamalielhere commented on package.json
> +    "trezor-connect": "8.2.9-beta.3",
can you revert this back. the package is excluded in test for now

2022-06-30 21:38 UTC, Abyscuit approved these changes

2022-07-01 06:07 UTC, hsurf22 approved these changes

2022-07-01 21:26 UTC, merged