Fix: BNB Return Values Not Valid
MyEtherWallet/MyEtherWallet pull request #3912
Opened 2022-06-10 23:07 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[ ] Add PR label

2022-06-14 23:17 UTC, gamalielhere approved these changes

2022-06-14 23:18 UTC, gamalielhere requested changes

2022-06-14 23:18 UTC, gamalielhere commented on src/main/errorHandler.js
> +    'Unexpected token value. Please refresh and try again.',
can you return just `Returned values aren't valid, did it run Out of Gas?`

2022-06-15 00:15 UTC, Abyscuit reviewed
Updated the response

2022-06-17 00:13 UTC, gamalielhere approved these changes

2022-06-24 23:26 UTC, NewCodeOnDaBlock approved these changes

2022-06-24 23:28 UTC, jmjles approved these changes

2022-06-24 23:30 UTC, andrewdahn approved these changes

2022-06-27 19:59 UTC, merged