fix: 🐛 failed to fetch pool api type error
MyEtherWallet/MyEtherWallet pull request #3917
Opened 2022-06-13 19:47 UTC by NewCodeOnDaBlock

### Fix

* \[x] Added entry to ./changelog
* \[x] Add PR label

2022-06-14 23:10 UTC, gamalielhere requested changes

2022-06-14 23:10 UTC, gamalielhere commented on package-test.js
> +const package = import('./package.json');
import wont work here as import is not supported by node natively.

2022-06-17 01:51 UTC, Abyscuit approved these changes

2022-06-21 19:17 UTC, gamalielhere commented on src/main/errorHandler.js
> +  'TypeError Failed to fetch': 'Failes to fetch incoming data'
fix typo

2022-06-21 19:58 UTC, gamalielhere approved these changes

2022-06-23 18:44 UTC, merged