feature: ✨ access wallet button merge
MyEtherWallet/MyEtherWallet pull request #3933
Opened 2022-06-16 18:59 UTC by NewCodeOnDaBlock

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Add test cases or procedure
* \[ ] Add PR label

2022-06-17 20:44 UTC, Abyscuit approved these changes

2022-06-21 19:15 UTC, andrewdahn approved these changes

2022-06-24 21:44 UTC, gamalielhere requested changes

2022-06-24 21:44 UTC, gamalielhere commented on src/modules/access-wallet/ModuleAccessWalletHardware.vue
> +      <!-- <access-wallet-ledger-x
remove unused code.

2022-06-24 21:44 UTC, gamalielhere commented on src/modules/access-wallet/ModuleAccessWalletHardware.vue
> +        // {
remove unused code.

2022-06-24 21:44 UTC, gamalielhere commented on src/modules/access-wallet/ModuleAccessWalletHardware.vue
> +            // if (this.onLedger) this.ledgerConnected = true;
remove unused code.

2022-06-24 21:44 UTC, gamalielhere commented on src/modules/access-wallet/hardware/components/AccessWalletLedger.vue
> +    // btnTitle() {
remove unused code.

2022-06-24 21:44 UTC, gamalielhere commented on src/modules/access-wallet/hardware/components/AccessWalletLedgerX.vue
> +    // btnTitle() {
remove unused code.

2022-07-13 20:55 UTC, merged