fix: 🐛 sentry error maxblock tobn
MyEtherWallet/MyEtherWallet pull request #3952
Opened 2022-06-23 15:07 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
* \[ ] Add PR label

2022-06-24 17:48 UTC, Abyscuit approved these changes

2022-07-13 04:17 UTC, hsurf22 approved these changes

2022-07-28 18:55 UTC, gamalielhere approved these changes

2022-07-29 21:41 UTC, gamalielhere requested changes
Catch the error before this is thrown. Not After

2022-09-02 17:47 UTC, gamalielhere requested changes

2022-09-02 17:47 UTC, gamalielhere commented on src/dapps/eth-blocks/components/BlockSearch.vue
> +      return max.gt(ZERO) ? max : '';
removing .toNumber() will break the ui as `maxBlock` is being rendered on line 8

2022-09-06 22:36 UTC, gamalielhere approved these changes

2022-09-09 18:03 UTC, andrewdahn approved these changes

2022-09-09 21:37 UTC, merged