devop: 🔧 nightwatch test for creating with mnemonic phrase
MyEtherWallet/MyEtherWallet pull request #3976
Opened 2022-07-01 18:09 UTC by andrewdahn

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-07-12 22:42 UTC, gamalielhere requested changes

2022-07-12 22:42 UTC, gamalielhere commented on tests/e2e/specs/create-wallet-mnemonic-test.js
> +const firstPhrases = {
can we change these to direct classes instead.

2022-07-13 23:59 UTC, gamalielhere approved these changes

2022-07-15 19:52 UTC, Abyscuit approved these changes

2022-07-15 21:25 UTC, merged