fix: create keysore image loading issue
MyEtherWallet/MyEtherWallet pull request #3980
Opened 2022-07-01 21:32 UTC by hsurf22

### Fix

* \[x] Added entry to ./changelog
* \[x] Add PR label

2022-07-11 19:19 UTC, andrewdahn approved these changes

2022-07-13 19:54 UTC, gamalielhere commented on src/modules/create-wallet/components/CreateWalletKeystore.vue
> +            style="max-width: 170px"
let's not hard code styles. please move it to classes.

2022-07-28 20:09 UTC, gamalielhere requested changes

2022-07-28 20:09 UTC, gamalielhere commented on src/modules/create-wallet/components/CreateWalletKeystore.vue
> +          style="max-width: 250px"
move to a class

2022-07-29 02:48 UTC, hsurf22 commented on src/modules/create-wallet/components/CreateWalletKeystore.vue
> +          style="max-width: 250px"
inline style removed

2022-07-29 21:03 UTC, gamalielhere approved these changes

2022-07-29 22:22 UTC, merged