Fix: max button when balance zero
MyEtherWallet/MyEtherWallet pull request #3982
Opened 2022-07-05 19:47 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[x] Add PR label

2022-07-08 01:08 UTC, gamalielhere requested changes

2022-07-08 01:08 UTC, gamalielhere commented on src/modules/swap/ModuleSwap.vue
> +        this.amountErrorMessage === this.errorMsgs.doNotOwnToken
you can use `this.availableBalance` to check if the balance is 0

2022-07-11 18:59 UTC, gamalielhere approved these changes

2022-07-13 04:15 UTC, hsurf22 approved these changes

2022-07-13 20:55 UTC, merged