devop: ledger prompt
MyEtherWallet/MyEtherWallet pull request #4031
Opened 2022-07-25 16:55 UTC by andrewdahn

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-07-26 23:29 UTC, gamalielhere approved these changes

2022-07-29 05:44 UTC, hsurf22 approved these changes

2022-08-04 02:58 UTC, gamalielhere requested changes

2022-08-04 02:58 UTC, gamalielhere commented on src/modules/access-wallet/hardware/handlers/hardwares/ledger/config.js
> +export const appNames = {
Can you add Go and XDC as well? they're options for the apps.

2022-08-08 19:05 UTC, gamalielhere approved these changes

2022-09-06 19:53 UTC, merged