Fix: buy tooltip daily limit
MyEtherWallet/MyEtherWallet pull request #4058
Opened 2022-07-29 23:53 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-08-04 03:13 UTC, gamalielhere approved these changes

2022-08-08 19:11 UTC, gamalielhere approved these changes

2022-08-08 19:11 UTC, gamalielhere requested changes

2022-08-08 19:11 UTC, gamalielhere commented on src/modules/moon-pay/components/MoonPayBuyComponent.vue
> +        this.max.simplex.lt(this.amount)
shouldn't this be using `maxVal`?

2022-08-08 21:27 UTC, gamalielhere requested changes

2022-08-08 21:27 UTC, gamalielhere commented on src/modules/moon-pay/components/MoonPayBuyComponent.vue
> +      const maxVal = Math.max(moonpayMax.toString(), simplexMax.toString());
move `maxVal` into a computed property since we're reusing it.

2022-08-09 18:15 UTC, gamalielhere approved these changes

2022-08-10 23:27 UTC, andrewdahn approved these changes

2022-08-11 01:33 UTC, merged