fix: fix eth blocks transaction fee wording
MyEtherWallet/MyEtherWallet pull request #4093
Opened 2022-08-10 04:22 UTC by hsurf22

### Fix

* \[x] Added entry to ./changelog
* \[x] Add PR label
   - fix eth blocks transaction fee wording
![Screenshot from 2022-08-09 21-22-15](https://user-images.githubusercontent.com/9893774/183815282-0d2d11a6-0975-4999-9529-8a70b3929117.png)

2022-08-10 18:55 UTC, Abyscuit approved these changes

2022-08-10 19:51 UTC, gamalielhere requested changes

2022-08-10 19:51 UTC, gamalielhere commented on src/components/MewSelect/MewSelect.vue
> +<template>
Please remove unused file.

2022-08-10 23:18 UTC, andrewdahn approved these changes

2022-08-24 06:21 UTC, hsurf22 commented on src/components/MewSelect/MewSelect.vue
> +<template>
Fixed!

2022-08-26 17:42 UTC, gamalielhere approved these changes

2022-08-29 18:59 UTC, merged