Fix: Ledger derivation path
MyEtherWallet/MyEtherWallet pull request #4117
Opened 2022-08-16 22:44 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-08-25 19:16 UTC, gamalielhere approved these changes

2022-08-26 17:31 UTC, NewCodeOnDaBlock approved these changes

2022-08-26 18:09 UTC, andrewdahn requested changes

2022-08-26 18:09 UTC, andrewdahn commented on src/modules/access-wallet/ModuleAccessWalletHardware.vue
> +        if (this.walletType === 'ledger') this.selectedPath = this.paths[0];
use `WALLET_TYPES.LEDGER` instead of the string `ledger`

2022-08-26 19:10 UTC, andrewdahn approved these changes

2022-09-20 21:20 UTC, merged