feature: ✨ unstoppable reverse resolver
MyEtherWallet/MyEtherWallet pull request #4118
Opened 2022-08-17 16:37 UTC by NewCodeOnDaBlock

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-09-06 22:45 UTC, gamalielhere requested changes

2022-09-06 22:45 UTC, gamalielhere commented on src/dapps/unstoppable-domains-dapp/metainfo.js
> +  networks: SUPPORTED_NETWORKS,
revert this.

2022-09-08 17:03 UTC, gamalielhere approved these changes

2022-09-12 20:55 UTC, gamalielhere approved these changes

2022-09-14 17:18 UTC, Abyscuit approved these changes

2022-09-14 18:27 UTC, merged