Fix: multiple ETH swap options
MyEtherWallet/MyEtherWallet pull request #4131
Opened 2022-08-23 17:16 UTC by Abyscuit

### Fix

* \[x] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[x] Add PR label

2022-08-23 17:39 UTC, gamalielhere requested changes

2022-08-23 17:39 UTC, gamalielhere commented on src/modules/swap/ModuleSwap.vue
> +        .filter(
This filter should be in the initial setup tokens since this only needs to happen once.

2022-08-26 17:46 UTC, gamalielhere approved these changes

2022-08-29 17:45 UTC, NewCodeOnDaBlock approved these changes

2022-08-29 18:59 UTC, merged