Fix: undefined swap tooltip
MyEtherWallet/MyEtherWallet pull request #4133
Opened 2022-08-23 21:59 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[ ] Add PR label

2022-08-25 19:35 UTC, gamalielhere approved these changes

2022-08-26 17:31 UTC, NewCodeOnDaBlock approved these changes

2022-08-26 18:10 UTC, andrewdahn approved these changes

2022-08-31 18:36 UTC, gamalielhere requested changes

2022-08-31 18:36 UTC, gamalielhere commented on src/views/TheWalletView.vue
> +      if (this.online && !this.isOfflineApp) this.setup();
move this change to the web3 watcher since web3 will change if the network changes.

2022-09-02 17:48 UTC, gamalielhere approved these changes

2022-09-08 17:05 UTC, gamalielhere approved these changes

2022-09-09 18:06 UTC, andrewdahn approved these changes

2022-09-09 21:37 UTC, merged