feature: ✨ verify ledger swap low
MyEtherWallet/MyEtherWallet pull request #4141
Opened 2022-08-25 19:28 UTC by NewCodeOnDaBlock

### Feature

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-08-26 20:31 UTC, gamalielhere requested changes

2022-08-26 20:31 UTC, gamalielhere commented on src/modules/confirmation/ModuleConfirmation.vue
> +      isLedger: false,
Remove this and it's instances. You're already checking for if the wallet is ledger via identifier

2022-08-29 19:46 UTC, gamalielhere approved these changes

2022-09-02 18:23 UTC, jmjles approved these changes

2022-09-02 18:23 UTC, andrewdahn approved these changes

2022-09-06 17:14 UTC, gamalielhere commented
Merged on #4129

2022-09-06 17:14 UTC, closed without merging