Fix: Aave NaN health factor
MyEtherWallet/MyEtherWallet pull request #4164
Opened 2022-09-03 08:30 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[x] Add PR label

2022-09-06 22:46 UTC, gamalielhere requested changes

2022-09-06 22:46 UTC, gamalielhere commented on src/dapps/aave-dapp/components/AaveSummary.vue
> +                  : +realHealthFactor > +this.nextHealthFactor
let's use BigNumber here

2022-09-08 17:04 UTC, gamalielhere approved these changes

2022-09-09 21:05 UTC, gamalielhere approved these changes

2022-09-14 18:14 UTC, gamalielhere approved these changes

2022-09-22 18:12 UTC, gamalielhere requested changes

2022-09-22 18:12 UTC, gamalielhere commented on src/dapps/aave-dapp/handlers/handlerAave.mixin.js
> -        this.trackDapp('depositCollateral');
Remove the handlerAnalytics mixin that's imported on this file as well.

2022-09-22 21:02 UTC, gamalielhere approved these changes

2022-09-26 18:21 UTC, andrewdahn approved these changes

2022-10-04 20:28 UTC, jmjles approved these changes

2022-10-04 21:53 UTC, merged