devop: 🔧 fix mew pop up top padding
MyEtherWallet/MyEtherWallet pull request #4167
Opened 2022-09-06 22:59 UTC by NewCodeOnDaBlock

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-09-08 17:10 UTC, gamalielhere requested changes
Mew component changes aren't needed for the task.

2022-09-09 17:47 UTC, gamalielhere requested changes
Change is only needed in the providers component.

2022-09-09 21:04 UTC, gamalielhere approved these changes

2022-09-15 09:47 UTC, hsurf22 approved these changes

2022-09-20 21:20 UTC, merged