devop: 🔧 fix qr pop up padding
MyEtherWallet/MyEtherWallet pull request #4168
Opened 2022-09-07 01:09 UTC by NewCodeOnDaBlock

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-09-08 17:17 UTC, gamalielhere requested changes

2022-09-08 17:17 UTC, gamalielhere commented on package.json
> +    "preinstall": "find node_modules -name \".git\" -exec rm -rf {} \\; || true && bash ./scripts/checklockconflicts.sh",
Please stop removing the resolutions.

2022-09-09 17:54 UTC, gamalielhere approved these changes

2022-09-15 09:47 UTC, hsurf22 approved these changes

2022-09-20 21:20 UTC, merged