fix: 🐛 missing dollar sign on swap
MyEtherWallet/MyEtherWallet pull request #4183
Opened 2022-09-13 04:01 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-09-13 21:22 UTC, Abyscuit requested changes

2022-09-13 21:22 UTC, Abyscuit commented on src/modules/swap/ModuleSwap.vue
> +            value = foundToken[0];
You need to `return item` here then outside of the filter call set `value = foundToken[0];`

2022-09-13 23:39 UTC, Abyscuit approved these changes

2022-09-15 05:22 UTC, hsurf22 approved these changes

2022-09-20 21:20 UTC, merged