fix: unavailable partner links
MyEtherWallet/MyEtherWallet pull request #4190
Opened 2022-09-14 03:37 UTC by hsurf22

### Fix

* \[x] Added entry to ./changelog
* \[x] Add PR label
   - unavailable partner link fixed

2022-09-14 18:21 UTC, gamalielhere requested changes

2022-09-14 18:21 UTC, gamalielhere commented on src/core/components/AppPartnersBlock.vue
> +        img: require('@/assets/images/partners/secalot.png')
Can we just remove it altogether?

2022-09-15 01:04 UTC, hsurf22 commented on src/core/components/AppPartnersBlock.vue
> +        img: require('@/assets/images/partners/secalot.png')
removed!

2022-09-15 18:44 UTC, andrewdahn approved these changes

2022-09-20 21:20 UTC, merged