Devop: switch offline network with JSON
MyEtherWallet/MyEtherWallet pull request #4222
Opened 2022-09-27 03:10 UTC by Abyscuit

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-09-27 22:08 UTC, gamalielhere requested changes

2022-09-27 22:08 UTC, gamalielhere commented on src/modules/send-offline/ModuleSendOffline.vue
> +          provider.then(() => {
you don't need to set token and balance for offline.

2022-09-28 20:38 UTC, gamalielhere approved these changes

2022-10-04 20:48 UTC, jmjles approved these changes

2022-10-04 21:53 UTC, merged