fix: 🐛 sentry type error balance card
MyEtherWallet/MyEtherWallet pull request #4237
Opened 2022-09-29 19:02 UTC by NewCodeOnDaBlock

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
* \[ ] Add PR label

2022-10-03 22:11 UTC, gamalielhere requested changes

2022-10-03 22:11 UTC, gamalielhere commented on src/modules/balance/ModuleBalanceCard.vue
> +      return `To verify, check the address on your ${this.instance?.meta.name} device & make sure it is the same address as the one shown below.`;
move the check to a computed property and return an empty string if instance is null.

2022-10-07 18:00 UTC, gamalielhere requested changes

2022-10-07 18:00 UTC, gamalielhere commented on package.json
> +    "protobufjs": "7.1.2",
remove the second one.

2022-10-12 19:22 UTC, gamalielhere requested changes

2022-10-18 21:05 UTC, Abyscuit approved these changes

2022-10-19 18:20 UTC, gamalielhere approved these changes

2022-10-19 23:10 UTC, merged