Fix: eth blocks date selection
MyEtherWallet/MyEtherWallet pull request #4290
Opened 2022-10-13 23:31 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[ ] Add PR label

2022-10-14 20:36 UTC, gamalielhere requested changes

2022-10-14 20:36 UTC, gamalielhere commented on src/dapps/eth-blocks/components/DateSelectorPopup.vue
> +              :max="new Date().toISOString()"
Let's move this in a computed property.

2022-10-19 19:03 UTC, gamalielhere approved these changes

2022-10-21 17:15 UTC, gamalielhere approved these changes

2022-11-01 18:31 UTC, andrewdahn approved these changes

2022-11-01 18:56 UTC, jmjles approved these changes

2022-11-02 01:14 UTC, merged