Devop: update network selection
MyEtherWallet/MyEtherWallet pull request #4408
Opened 2022-12-06 00:42 UTC by Abyscuit

### Devop

* \[ ] Added entry to ./changelog
* \[ ] Add PR label

2022-12-07 17:22 UTC, gamalielhere requested changes

2022-12-07 17:22 UTC, gamalielhere commented on src/core/router/routes-offline-wallet.js
> +    // {
Remove commented code.

2022-12-07 17:22 UTC, gamalielhere commented on src/core/router/routes-wallet.js
> +    // {
Here too.

2022-12-07 17:22 UTC, gamalielhere commented on src/views/layouts-wallet/TheSwapLayout.vue
> -      this.trackSwap('switchingNetworkOnSwap');
Move this to check when the popup is being opened in the swap page.

2022-12-08 20:58 UTC, gamalielhere requested changes

2022-12-08 20:58 UTC, gamalielhere commented on src/views/layouts-wallet/TheSwapLayout.vue
> +    if (to.name !== ROUTES_WALLET.SWAP.NAME) {
Route doesn't change anymore.  Watch the "isOpenNetworkOverlay" instead, check if current route is swap, then fire event.

2022-12-08 20:58 UTC, gamalielhere commented on src/modules/network/ModuleNetwork.vue
> +    // this.openNetworkOverlayOnLoad();
Remove commented code.

2022-12-09 00:50 UTC, gamalielhere approved these changes

2022-12-20 17:11 UTC, jmjles approved these changes

2022-12-20 19:58 UTC, merged