Fix: clear after signing message
MyEtherWallet/MyEtherWallet pull request #4440
Opened 2022-12-20 23:37 UTC by Abyscuit

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[ ] Add PR label

2022-12-21 20:14 UTC, gamalielhere requested changes

2022-12-21 20:14 UTC, gamalielhere commented on src/modules/message/ModuleMessageSign.vue
> +            this.instance.errorHandler(e.message);
should probably clear here too

2022-12-27 19:01 UTC, gamalielhere approved these changes

2022-12-29 20:14 UTC, hsurf22 approved these changes

2023-01-04 20:14 UTC, jmjles approved these changes

2023-01-06 18:43 UTC, merged