UI: Address clipping
MyEtherWallet/MyEtherWallet pull request #4481
Opened 2023-01-12 00:23 UTC by jmjles

### Fix

* \[ ] Added entry to ./changelog
* \[ ] Is this a user submitted bug?
  * \[ ] Link to issue:
* \[ ] Add PR label

2023-01-12 19:17 UTC, gamalielhere requested changes

2023-01-12 19:17 UTC, gamalielhere commented on src/modules/message/ModuleMessageVerify.vue
> +.Signer {
keep classes lowercase

2023-01-13 19:58 UTC, gamalielhere approved these changes

2023-01-24 19:19 UTC, Abyscuit approved these changes

2023-02-21 22:11 UTC, merged