devop: add flyover dapp
MyEtherWallet/MyEtherWallet pull request #4678
Opened 2023-07-24 12:46 UTC by ahsan-javaiid

### Devop

* \[X] Added entry to ./changelog
* \[ ] Add PR label

### Description
Added flyover dApp for Rootstock network based on flyover protocol. This app provides easier way of transfer of BTC between the Bitcoin mainchain and the Rootstock sidechain with RIF Flyover protocol within the wallet.

Flyover website: https://flyover.rifos.org/

### Demo

https://github.com/MyEtherWallet/MyEtherWallet/assets/104683677/8b86a4b8-8098-48d8-94ba-ae484729a6c1

https://github.com/MyEtherWallet/MyEtherWallet/assets/104683677/6383c1e0-663c-4229-acc3-5c81d9799986

2023-12-20 10:25 UTC, ahsan-javaiid commented
Hi @gamalielhere

This pull request (Flyover dApp) is ready to merge. Apologies for taking so long on this. Flyover team updated the protocol and now it's ready to review and merge. 
The liquidity on flyover is limited so just bare with that (A user could try later if in case he face not enough liquidity notification).

Feel free to review and merge the pull request.

cc: @alepc253

2024-01-16 18:30 UTC, gamalielhere requested changes

2024-01-16 19:58 UTC, ahsan-javaiid commented on src/dapps/flyover-dapp/components/pegout/GetQuote.vue
> +          detail = e.details.maxValueTotransfer / 10 ** 18;
Done!

2024-01-16 19:59 UTC, ahsan-javaiid commented on src/dapps/flyover-dapp/components/pegout/GetQuote.vue
> +        valueToTransfer: parseFloat(this.amount) * 10 ** 18
Done!

2024-01-16 19:59 UTC, ahsan-javaiid commented on src/dapps/flyover-dapp/modules/ModulePegout.vue
> +        this.quoteAmount = val.quote.value / 10 ** 18;
Done!

2024-01-16 19:59 UTC, ahsan-javaiid commented on src/dapps/flyover-dapp/components/pegout/DepositFunds.vue
> +  data() {
Done!

2024-01-17 20:28 UTC, merged